Proposal: Ternary Operator
fiveagency/ios-swift-guide pull request #11
Opened 2022-07-07 13:02 UTC by amarkotic

2022-07-07 13:06 UTC, lihter submitted a review, later dismissed

2022-07-07 13:34 UTC, iandric submitted a review, later dismissed

2022-07-07 14:04 UTC, BornaR submitted a review, later dismissed

2022-07-07 14:15 UTC, lukan98 commented on Code Style/README.md
> +When assigning value under a specific condition, use the ternary operator instead of `if-else statement` whenever possible. Anything that outputs `true` or `false` can be considered a `condition`.
When assigning **a** value [...] instead of **an** `if-else statement`

2022-07-07 14:17 UTC, lukan98 commented on Code Style/README.md
> +When using a ternary operator that doesn't fit into 120 characters, use a multiline ternary operator. The second and the third line of the multiline ternary operator must be indented by one tab.
Maybe leave out the "by one tab" part since we technically indent using spaces 🙂

2022-07-07 14:24 UTC, dorastipkovic submitted a review, later dismissed

2022-07-07 15:42 UTC, amarkotic commented on Code Style/README.md
> +When using a ternary operator that doesn't fit into 120 characters, use a multiline ternary operator. The second and the third line of the multiline ternary operator must be indented by one tab.
We can compromise on mentioning both spaces and tab.

2022-07-07 15:59 UTC, lukan98 submitted a review, later dismissed

2022-07-11 14:39 UTC, istaudacher approved these changes

2022-08-16 07:54 UTC, iandric commented on Code Style/README.md
> +    valueWithVeryLongName1 :
Doesn't Xcode format such expressions without the tab/spaces; i.e. the way we are supposed to avoid? Seems like unnecessary work to manually align such lines while coding. Wondering if such formatting rules shouldn't just be handled by SwiftLint and such?

2022-08-17 12:03 UTC, amarkotic commented on Code Style/README.md
> +    valueWithVeryLongName1 :
@dnikolic98 will write a rule in SwiftLint regarding this so we'll be safe

2022-08-17 16:15 UTC, lukan98 requested changes

2022-08-17 16:15 UTC, lukan98 commented on Code Style/README.md
> +If the value to assign is being calculated in a separate function which returns a value, ternary should be used when calling those functions.
If the value to assign is being calculated in a separate function which returns a value, **the** ternary **operator** should be used when calling those functions.

2022-08-17 16:15 UTC, lukan98 commented on Code Style/README.md
> +Ternary operator must not be misused for calling functions that return void.
**The** ternary operator

2022-08-23 17:48 UTC, lukan98 approved these changes

2022-08-29 10:51 UTC, iandric approved these changes
lgtm 👍

2022-09-08 13:47 UTC, merged