Proposal - Standalone namespacing type
fiveagency/ios-swift-guide pull request #12
Opened 2022-08-03 12:25 UTC by iandric

2022-08-03 14:47 UTC, istaudacher requested changes

2022-08-03 14:47 UTC, istaudacher commented on Code Style/README.md
> +    static let height: CGFloat { 10 }
Why not `static let height: CGFloat = 10`?
Also, per spacing rules, there should be a newline after line 384 and before 387.

2022-08-03 14:58 UTC, iandric commented on Code Style/README.md
> +    static let height: CGFloat { 10 }
Yup, obviously = instead of {}, this being a let. Was focusing on the namespace part, thanks!
Will also update spacing.

2022-08-03 15:05 UTC, istaudacher approved these changes
Looks good!
Let's see what others think.

2022-08-03 15:51 UTC, lukan98 approved these changes

2022-08-13 09:18 UTC, amarkotic approved these changes

2022-08-16 07:32 UTC, lihter approved these changes

2022-08-16 07:35 UTC, merged