Proposal: Limit build times for functions and expressions
fiveagency/ios-swift-guide pull request #16
Opened 2022-09-27 13:27 UTC by amarkotic

2022-09-28 12:13 UTC, istaudacher submitted a review, later dismissed

2022-09-28 15:09 UTC, marinzg submitted a review, later dismissed

2022-09-29 08:31 UTC, kristianFive approved these changes

2022-09-29 08:44 UTC, lukan98 requested changes

2022-09-29 08:44 UTC, lukan98 commented on Project Settings/README.md
> +Both flags receive a value in milliseconds, which represents a build time limit. Suggested limit is `100ms` for both flags. The warning is displayed if that limit is exceeded.
**The** suggested limit is `100ms` for both flags.

2022-09-29 11:03 UTC, iandric approved these changes

2022-09-30 13:07 UTC, merged